# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: guess-game
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kimidomaru/k8s_puc:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
      #  livenessProbe:
      #    httpGet:
      #      path: /health
      #      port: 5000
      #    initialDelaySeconds: 10
      #    periodSeconds: 5
      #  readinessProbe:
      #    httpGet:
      #      path: /health
      #      port: 5000
      #    initialDelaySeconds: 10
      #    periodSeconds: 5
---
# service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: guess-game
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
#hpa
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: guess-game
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50