# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: guess-game
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres"
---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: guess-game
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi